version: 2
jobs:
  epitest:
    docker:
      - image: epitechcontent/epitest-docker
    steps:
      - checkout
      - run:
          name: Basic test
          command: cd dashboard && npm install && CI=false npm run build

#           name: Unit Tests Execution
#           command: ./unit_tests.out -j 1 --xml=tests/results.xml --always-succeed
#       - store_test_results:
#           path: .

workflows:
  version: 2
  commit:
    jobs:
      - epitest
  planned:
    triggers:
      - schedule:
          cron: "0 21 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - epitest
